### PR TITLE
chore(project): remove shelljs library

### LINKED ISSUE #1189: [chore]: remove shelljs library
We don't really need shelljs as a library to do something for us.

There is no need to install another library to solve the problem as we can write some tools to replace it.

https://github.com/netless-io/flat/blob/a2ed31333867919798ff61a1f3dfeb3416b0f449/package.json#L35

https://github.com/netless-io/flat/blob/a2ed31333867919798ff61a1f3dfeb3416b0f449/desktop/main-app/scripts/agora/mv-addon.js#L7

remove shelljs command:

```shell
# Project root path
yarn remove shelljs -W
```

### PR DESCRIPTION
**Pull request by Gavin0x0**
- Fixes #1189 
- @bestony
- Its my first time to create a PR, thanks for providing this opportunity for me to participate in open source projects

### CODE REVIEW

**Review by BlackHole1 — APPROVED** [review]
LGTM. Thank you for the PR! It helps a lot!

Please wait a moment, I need to test it locally to make sure it works (it looks fine to me if I just look at the code. To be more sure, I need to do actual local testing)

**Comment by BlackHole1** [comment]
It works without any problems!
Thank you for your contribution to the open source community.

**Comment by bestony** [comment]
Hi, @BlackHole1 ,please send your address, phone number, and name to my email address (bestony@linux.com), i will send you DAO.FM gift.

**Comment by BlackHole1** [comment]
> Hi, @BlackHole1 ,please send your address, phone number, and name to my email address ([bestony@linux.com](mailto:bestony@linux.com)), i will send you DAO.FM gift.

I think you at the wrong person. You should be looking for @levi-oh

**Comment by bestony** [comment]
Hi, @levi-oh ,please send your address, phone number, and name to my email address (bestony@linux.com), i will send you DAO.FM gift.

**Pull request merged**
