### PR TITLE
refactor(web): add mobile join page

### PR DESCRIPTION
**Pull request by hyrious**

### CODE REVIEW

**Comment by BlackHole1** [comment]
This feature should not be placed in the flat project.

move to https://github.com/netless-io/flat-landing-page

**Comment by hyrious** [comment]
@BlackHole1 This page exists here because the **share url** points to flat-web, in which case mobile users will click on the link and see this page.

**Comment by BlackHole1** [comment]
waht is share url? is invite url?

**Comment by hyrious** [comment]
> waht is share url? is invite url?

Yes.

**Review by BlackHole1 — APPROVED** [review]

**Pull request merged**
