### PR TITLE
fix(renderer-app): close cloud storage panel fail after insert file

### PR DESCRIPTION
**Pull request by Cheerego7**

### CODE REVIEW

**Review by BlackHole1 — COMMENTED** [review]
forget change web?

**Comment by hyrious** [comment]
> forget change web?

web has no such issue.

**Comment by Cheerego7** [comment]
> 

only the renderer-app has this problem

**Comment by BlackHole1** [comment]
> > forget change web?
> 
> web has no such issue.



> > 
> 
> only the renderer-app has this problem

@Cheerego7 @hyrious What is the reason why only the renderer will have this problem?

**Comment by BlackHole1** [comment]
oh. I got it

https://github.com/netless-io/flat/blob/a2ed31333867919798ff61a1f3dfeb3416b0f449/web/flat-web/src/pages/CloudStoragePage/CloudStoragePanel.tsx#L18

**Review by BlackHole1 — APPROVED** [review]
LGTM

**Pull request merged**
