### PR TITLE
chore(flat-services): remove AgoraRTM deprecated 'enableHistoricalMessaging' property

### PR DESCRIPTION
**Pull request by shunyue1320**

### CODE REVIEW

**Comment by BlackHole1** [comment]
@hyrious

**Comment by hyrious** [comment]
RTM deprecated this feature several versions ago because it cannot guarantee the completeness of history. However the chat component in Flat is currently built on this feature. We have to find an alternative service before we could merge this PR (which makes the chat service in Flat half broken).

**Comment by BlackHole1** [comment]
Close PR first until we find a replacement service. Anyway thank you for your PR!

**Comment by shunyue1320** [comment]
thanks

**Pull request closed without merging**
