### PR TITLE
chore(eslint): add `eslint-plugin-eslint-comments`

### PR DESCRIPTION
**Pull request by LitoMore**
### Benefits

- To disallow unlimited disabling.
- To disallow unused disabling.
- To disallow non-effect enabling.
- To require rule IDs for disabling and enabling.

### Reference

https://github.com/mysticatea/eslint-plugin-eslint-comments

### Unused rules?

I found that we disabled some rules at top in most of files:

- `react/display-name`
- `no-redeclare`
- `react/jsx-no-target-blank`

If we don't want that rule, just disable it in `.eslint.common.js`. Otherwise, we should use `eslint-disable-next-line` instead of disabling the rule for the whole file.

I'm using `/* eslint rule-name: off */` instead of `/* eslint-disable rule-name */` in the PR. We could file another PR if we want to drop some rules or change them to `eslint-disable-next-line`.

### CODE REVIEW

**Comment by BlackHole1** [comment]
What is the difference between `/* eslint rule-name: off */` and  `/* eslint-disable rule-name */`

**Comment by LitoMore** [comment]
`/* eslint rule-name: off */` is only used for configure the whole file.

But for `/* eslint-disable rule-name */`, its use case should be:


```js
...
const var1 = {
	/*  eslint-disable camelcase */
	camel_case: 10,
	foo_bar: 10,
	flat_name: 10,
	/* eslint-disable camelcase */
}
...
const foo_bar = 10 // ❌ Error
```

We should enable it again for the rest of codes.

**Review by BlackHole1 — APPROVED** [review]
LGTM

**Comment by LitoMore** [comment]
There is no conflict with the main branch, we don't have to update this PR every time.

**Comment by BlackHole1** [comment]
> There is no conflict with the main branch, we don't have to update this PR every time.

see:
图片

**Comment by LitoMore** [comment]
Yes, we don't have to do this. Just leave that button there. I received a lot of unused notifications from email and Slack, that's a little bit annoying. There is no difference whether you do not update the feature branch for merging.

**Comment by LitoMore** [comment]
Only if we want to continue some work with the latest code on the feature branch, then update the branch.

**Comment by BlackHole1** [comment]
Ok, I will try what you said next time.

**Pull request merged**
