### PR TITLE
[WIP] chore(flat-components): change wepack to vite

### PR DESCRIPTION
**Pull request by Cyberhan123**
This pull request is still process on,here is the discussion https://github.com/netless-io/flat/issues/1143

### CODE REVIEW

**Comment by shunyue1320** [comment]
Whether to consider [storybook-builder-vite](https://github.com/eirslett/storybook-builder-vite/tree/main/packages/storybook-builder-vite)

**Comment by Cyberhan123** [comment]
> Whether to consider [storybook-builder-vite](https://github.com/eirslett/storybook-builder-vite/tree/main/packages/storybook-builder-vite)

Thanks, let me test if it works.

**Comment by Cyberhan123** [comment]
> Whether to consider [storybook-builder-vite](https://github.com/eirslett/storybook-builder-vite/tree/main/packages/storybook-builder-vite)

@shunyue1320  please see https://github.com/netless-io/flat/issues/1143#issuecomment-981253929，to get more detail

**Comment by Cyberhan123** [comment]
I'll close the push request and wait for me to finish before making it .

**Pull request closed without merging**
