### PR TITLE
docs(readme): use gif preview image

### PR DESCRIPTION
**Pull request by BlackHole1**

### CODE REVIEW

**Comment by LitoMore** [comment]
I don't think it's a good idea. See https://github.com/netless-io/flat/pull/1263#issuecomment-1003300836.

**Comment by BlackHole1** [comment]
> I don't think it's a good idea. See [#1263 (comment)](https://github.com/netless-io/flat/pull/1263#issuecomment-1003300836).

This proposal has recently been revived by our product manager(@Leooeloel ). 🙇‍♂️

Let me explain why in a nutshell 💬:
1. We have received a lot of feedback from users that the preview images in the README do not clearly describe the functionality of the software and this is leading to a loss of users. 🙅
2. We don't have more time to complete the video in English and Chinese at the moment. ⌛️
3. This is a temporary solution, it is not permanent. We will take the time to record the video after the Chinese New Year has passed. ⏲

**Comment by LitoMore** [comment]
Like https://github.com/microsoft/vscode, https://github.com/wulkano/Kap and https://github.com/OpenEmu/OpenEmu do. They never put a GIF into the readme.

You will make readme worse if you add a bad quality GIF to the readme.

And I don't think the loss of our users has anything to do with the GitHub repo, we should be improving our homepage, not here.

**Comment by BlackHole1** [comment]
cc: @Leooeloel

**Comment by Leooeloel** [comment]
Out of instinct I would like to explain a few things, but out of my heart I agree with you. 

Ok, please help me close this PR.

@LitoMore @BlackHole1

**Pull request closed without merging**
