### PR TITLE
refactor(web): improve useRef type

### PR DESCRIPTION
**Pull request by BlackHole1**
remove useless type. see https://github.com/netless-io/flat/pull/1113#discussion_r754009600

### CODE REVIEW

**Comment by LitoMore** [comment]
```shell
git grep ' | null>'
```

Other usages can be cleaned up.

**Comment by BlackHole1** [comment]
> ```shell
> 
> git grep ' | null>'
> 
> ```
> 
> 
> 
> Other usages can be cleaned up.

okey

**Review by hyrious — APPROVED** [review]

**Comment by BlackHole1** [comment]
regex modification to `useRef<.*null.*\(`

**Comment by BlackHole1** [comment]
there are currently no redundant changes required
see: 
图片

图片

cc: @LitoMore

**Review by LitoMore — APPROVED** [review]

**Comment by LitoMore** [comment]
CleanShot 2021-11-22 at 16 32 06@2x

We can turn off the `Require branches to be up to date before merging` option. That's nit for merging.

**Comment by BlackHole1** [comment]
> CleanShot 2021-11-22 at 16 32 06@2x
> 
> We can turn off the `Require branches to be up to date before merging` option. That's nit for merging.

done. @LitoMore

**Pull request merged**
