### PR TITLE
chore(eslint): optimize imports

### PR DESCRIPTION
**Pull request by LitoMore**
### Changes

- Add [`sort-imports`](https://eslint.org/docs/rules/sort-imports)
- Add [`import/order`](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md)
- Add [`import/no-duplicates`](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-duplicates.md)
- Add [`@typescript-eslint/consistent-type-imports`](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/consistent-type-imports.md)

I moved all unassigned imports (CSS/Less/MP3) to the bottom for a better visual.

### When to disable it?

And I am using `eslint-disable-next-line import/order` to allow our unassigned sibling CSS/Less imports after those imports from package. Just to avoid some style override issues. Here is an example:

```js
import 'videojs/example.css';
// eslint-disable-next-line import/order
import './style.less';
```

I don't want to [take too much effort](https://github.com/import-js/eslint-plugin-import/issues/1239#issuecomment-716683648) on [pathGroups](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md#pathgroups-array-of-objects). Using `eslint-disable-next-line import/order` is easilier.

### Tips

Use the split diff view for better visual.

image

### Plan

I'm going to enable ESLint for all workspaces and root files in another PR.

### CODE REVIEW

**Comment by BlackHole1** [comment]
Wow. Thank you for the PR! This is something I've always wanted to do! 🤩

Please wait a moment, I need to test this RP locally

**Comment by BlackHole1** [comment]
@LitoMore Can you resolve the conflict?

**Comment by LitoMore** [comment]
@BlackHole1 Conflict has been resolved.

Please hold on other PRs until this one get merged.

**Comment by crimx** [comment]
How about [eslint-plugin-simple-import-sort](https://github.com/lydell/eslint-plugin-simple-import-sort#sort-order) which [keeps the order of side-effect imports](https://github.com/lydell/eslint-plugin-simple-import-sort#example-1).

**Comment by LitoMore** [comment]
@crimx You can create another PR and try to replace them (based on this PR). I'm not going to take too much effort into it.

**Comment by BlackHole1** [comment]
I will be responsible for the revision of this PR as @LitoMore  does not have the extra time to do it

**Comment by LitoMore** [comment]
We can merge. Then change to `eslint-plugin-simple-import-sort`.

**Comment by BlackHole1** [comment]
Hey @LitoMore 👋
The other day, I communicated with @crimx  about this PR.
Currently this PR cannot be merged immediately as this PR automatically modifies the order in which some style files are introduced, which may result in style errors.
So to be on the safe side, we should address this issue in the current PR rather than opening a new one to address it.🙇

**Comment by LitoMore** [comment]
OK. Closing in favor of the new one.

**Pull request closed without merging**
