### PR TITLE
fix(web): force wait rtc join

### PR DESCRIPTION
**Pull request by hyrious**

### CODE REVIEW

**Review by BlackHole1 — DISMISSED** [review]
nice!

**Review by Cheerego7 — DISMISSED** [review]

**Comment by BlackHole1** [comment]
should this PR be withdrawn?
https://github.com/netless-io/flat/pull/1035

**Comment by hyrious** [comment]
> should this PR be withdrawn? #1035

Anyway, removing a `!` is a good refactoring. Keep it.

**Review by BlackHole1 — APPROVED** [review]

**Comment by BlackHole1** [comment]
> > should this PR be withdrawn? #1035
> 
> Anyway, removing a `!` is a good refactoring. Keep it.

ok

**Pull request merged**
