### PR TITLE
chore(lint): improve cspell and lint-stage

### PR DESCRIPTION
**Pull request by BlackHole1**
see: https://github.com/okonet/lint-staged/tree/d327873b1c0b6fbdeb6fd276e523043d51d6de37#how-to-use-lint-staged-in-a-multi-package-monorepo

image

### CODE REVIEW

**Comment by crimx** [comment]
and `.tsx` ?

**Comment by BlackHole1** [comment]
> and `.tsx` ?

See: https://github.com/netless-io/flat/pull/1464/files#diff-f3c0adcc5f5e3aa60e21fab991e935cad7eeef77d93d12b9260950bf6a4b8104R3
image


@crimx

**Comment by LitoMore** [comment]
Then we should install the `lint-staged` to the root.

**Comment by BlackHole1** [comment]
> Then we should install the `lint-staged` to the root.

Already modified in the previous PR. https://github.com/netless-io/flat/pull/1442

**Review by hyrious — DISMISSED** [review]

**Comment by crimx** [comment]
> > and `.tsx` ?
> 
> See: https://github.com/netless-io/flat/pull/1464/files#diff-f3c0adcc5f5e3aa60e21fab991e935cad7eeef77d93d12b9260950bf6a4b8104R3 image
> 
> @crimx

I meant eslint and prettier

**Review by hyrious — DISMISSED** [review]

**Review by hyrious — APPROVED** [review]

**Review by crimx — APPROVED** [review]

**Pull request merged**
