### PR TITLE
chore(readme): update image

### PR DESCRIPTION
**Pull request by Cheerego7**

### CODE REVIEW

**Comment by BlackHole1** [comment]
gif file size is so large

**13.7MB**

**Comment by BlackHole1** [comment]
This PR is need wait #1262 merged

Also, shouldn't we split the gif into several separate gifs instead of one. And put them in a wike or docs?

cc: @LitoMore @yamasite

**Comment by LitoMore** [comment]
We don't need this in readme.

You could provide a video on our official website instead of the readme.

And please use MP4 instead of GIF for the presentation. MP4 has better performance and smaller compression size.

**Comment by Cheerego7** [comment]
> We don't need this in readme.
> 
> You could provide a video on our official website instead of the readme.
> 
> And please use MP4 instead of GIF for the presentation. MP4 has better performance and smaller compression size.

yep, we will add video in the future

**Pull request closed without merging**
